version: '3.9'

services:

  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongodb://root:dajdoiwjwT_313131@mongo:27017

    depends_on:
      - mongo

  mongo:
    container_name:
      mongo
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dajdoiwjwT_313131

    volumes:
      - mongodb_data:/data/db

    ports:
      - "27017:27017"

volumes:
  mongodb_data:
