http:
  port: "8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 3m
  max_header_bytes: 65000

auth:
  password_cost_bcrypt: 13
  access_token_ttl: 10m
  refresh_token_ttl: 72h

mongo:
  database: identity

jwt:
  refresh_token_cost_bcrypt: 10